---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install Gnocchi components
  hosts: gnocchi_all
  user: root
  environment: "{{ deployment_environment_variables | default({}) }}"
  vars_files:
    - "defaults/{{ install_method }}_install.yml"
  tags:
    - gnocchi
  pre_tasks:
    - include: "common-tasks/os-{{ container_tech | default('lxc') }}-container-setup.yml"
      vars:
        list_of_bind_mounts: "{{ gnocchi_container_bind_mounts }}"
      static: no
      when:
        - (gnocchi_storage_driver == "file") or (gnocchi_storage_driver is not defined)
        - not is_metal

    - include: "common-tasks/os-{{ container_tech | default('lxc') }}-container-setup.yml"
      static: no
      when:
        - not is_metal
        - gnocchi_storage_driver is defined
        - gnocchi_storage_driver != "file"

    - include: common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-gnocchi"
            dest: "/var/log/gnocchi"

    - include: common-tasks/unbound-clients.yml
      static: no
      when:
        - hostvars['localhost']['resolvconf_enabled'] | bool
  roles:
    - role: "ceph_client"
      openstack_service_system_user: "{{ gnocchi_system_user_name }}"
      openstack_service_venv_bin: ""
      when:
        - inventory_hostname in groups['gnocchi_api']
        - (gnocchi_storage_driver | default('none') | lower == 'ceph')
      tags:
        - ceph

    - role: "os_gnocchi"

  post_tasks:
    - include_tasks: "common-tasks/rsyslog-client.yml"
      vars:
        rsyslog_client_log_rotate_file: gnocchi_log_rotate
        rsyslog_client_log_dir: "/var/log/gnocchi"
        rsyslog_client_config_name: "99-gnocchi-rsyslog-client.conf"
