---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Installation and setup of Swift
  hosts: swift_all:swift_remote_all
  gather_facts: "{{ osa_gather_facts | default(True) }}"
  user: root
  vars_files:
    - "defaults/{{ install_method }}_install.yml"
  pre_tasks:
    - include: "common-tasks/os-{{ container_tech | default('lxc') }}-container-setup.yml"
      static: no
      vars:
        extra_container_config_no_restart:
          - "lxc.start.order=39"
      when: not is_metal

    - include: common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-swift"
            dest: "/var/log/swift"
    - include: common-tasks/unbound-clients.yml
      static: no
      when:
        - hostvars['localhost']['resolvconf_enabled'] | bool

  roles:
    - role: "os_swift"
      swift_do_setup: True
      swift_do_sync: True
  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - swift

- name: Installation and setup of Swift
  hosts: swift_all
  user: root
  roles:
    - role: "system_crontab_coordination"
      tags:
        - crontab

  post_tasks:
    - include_tasks: "common-tasks/rsyslog-client.yml"
      vars:
        rsyslog_client_log_rotate_file: swift_log_rotate
        rsyslog_client_log_dir: "/var/log/swift"
        rsyslog_client_config_name: "99-swift-rsyslog-client.conf"
        rsyslog_client_log_files:
          - /var/log/rsyncd.log

  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - swift
