---
- hosts: "{{ openstack_host_group|default('hosts') }}"
  remote_user: ubuntu
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure python is installed
      register: result
      raw: |
        if which apt-get >/dev/null && ! which python >/dev/null ; then
          apt-get -y install python
          exit 2
        else
          exit 0
        fi
      changed_when: "result.rc == 2"
      failed_when: "result.rc not in [0, 2]"
    - name: "Set authorized key took from file"
      authorized_key:
        user: root
        state: present
        exclusive: yes
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: "compute node dummy eth12"
  hosts: "nova_compute"
  become: true
  roles:
    - role: "systemd_networkd"
      systemd_interface_cleanup: false
      systemd_run_networkd: true
      systemd_netdevs:
        - NetDev:
            Name: eth12
            Kind: dummy
