- hosts: all
  tasks:
    - name: Run gate-check-commit.sh script
      become: yes
      become_user: root
      shell: >-
        scripts/gate-check-commit.sh {{ scenario }} {{ action }} {{ install_method }}
      args:
        chdir: "src/git.openstack.org/openstack/openstack-ansible"
        executable: /bin/bash
      environment:
        # ZUUL_SRC_PATH is used by tests/get-ansible-role-requirements to
        # where the CI provided git sources were cloned.
        ZUUL_SRC_PATH: "{{ ansible_user_dir }}/src"
        ANSIBLE_PACKAGE: "{{ ansible_package | default('') }}"
