---
# Copyright 2017, Ravi Kumar Boyapati <rboyapat@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ceph default list of bind mounts
ceph_container_bind_mounts:
  - bind_dir_path: "/var/lib/ceph"
    mount_path: "/openstack/{{ inventory_hostname }}"

# To extend ceph_conf_overrides use the ceph_conf_overrides_custom which will
# combine any ceph_conf_overrides with other RGW specific overrides.
ceph_conf_overrides_custom: {}
ceph_conf_overrides: "{{ (ceph_conf_overrides_rgw | default({})) | combine(ceph_conf_overrides_custom, recursive=True) }}"

# Disable the NFS gateway PPA and package install by default as it is not
# needed.
nfs_file_gw: False
nfs_obj_gw: False

# NTP in an OSA environment is handled by ansible-hardening using chrony
# ceph-ansible's default enabling of ntpd conflicts with the OSA defaults
ntp_service_enabled: False
